title: Pradlenka – restaurant & bar
short_title: Pradlenka
description: >
  The Pradlenka restaurant is also known under its former name Wash Café.
  Looking back into history, in the place where Pradlenka is located, 
  you will find a real laundry. Even today, next to the bar and 
  restaurant with great food and drinks, we run a public laundry here.
description-cs: >
  Restauraci Pradlenka můžete znát pod dřívějším názvem Wash Café. 
  Když se vrátíme k historii prostor, ve kterých se Pradlenka nachází, 
  skutečně zde dříve prádelna byla. I dnes tu vedle baru a restaurace 
  se skvělým jídlem a pitím najdete veřejnou prádelnu.
baseurl:
permalink: "/:path/"
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: home
collections:
  pages:
    output: true
# tag_page_layout: tag_page
# tag_page_dir: tag
jekyll-archives:
  enabled: all
  layout: "archive"
css_version: knceasdft
js_version: knceasdft
meta_version: knceasdft
exclude:
  - .*/
  - _*/
  - CNAME
  - Gemfile*
gems:
  - jekyll-menus
  - jekyll-feed
  - jekyll-archives
