title: Pradlenka – restaurant & bar
short_title: Pradlenka
description: >
  Restauraci Pradlenka můžete znát pod dřívějším názvem Wash Café. 
  Když se vrátíme k historii prostor, ve kterých se Pradlenka nachází, 
  skutečně zde dříve prádelna byla. I dnes tu vedle baru a restaurace 
  se skvělým jídlem a pitím najdete veřejnou prádelnu.
baseurl:
permalink: "/:path/"
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: home
collections:
  pages:
    output: true
# tag_page_layout: tag_page
# tag_page_dir: tag
jekyll-archives:
  enabled: all
  layout: "archive"
gems:
  - jekyll-menus
  - jekyll-feed
  - jekyll-archives
